# Generated by Django 4.0 on 2021-12-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='images/')),
                ('BusinessName', models.CharField(default='null', max_length=70)),
                ('description', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
                ('Date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to='account.userbase')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-Date_added',),
            },
        ),
    ]
